theme: jekyll-theme-minimal
title: Weder Fail noch Lobgesang: Nicht-eindeutige Wertung von Literatur im Digitalen Raum (Panel Germanistentag22)
logo: assets/pics/stars.jpg
description: "pic by Towfiqu barbhuiya (unsplash)"
